import {
  User,
  UserRound,
  UserCircle2,
  Smile,
  Heart,
  Star,
  Sparkles,
  Music,
  Music2,
  Mic2,
  Flame,
  Zap,
  Trophy,
  Target,
  Compass,
  Feather,
  Flower2,
  Leaf,
  Moon,
  Sun,
  Cloud,
  Mountain,
  Waves,
  Crown,
  Gem,
  Rocket,
  Wind,
  type LucideIcon,
} from 'lucide-react';

/** Curated, professional avatar icon set (lucide-react — already a
 * dependency, no new asset pipeline). Keys are what gets stored as
 * `icon:<key>` in User.avatarUrl — see Avatar.tsx and AvatarPicker.tsx. */
export const AVATAR_ICONS: Record<string, LucideIcon> = {
  user: User,
  'user-round': UserRound,
  'user-circle': UserCircle2,
  smile: Smile,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
  music: Music,
  'music-note': Music2,
  mic: Mic2,
  flame: Flame,
  zap: Zap,
  trophy: Trophy,
  target: Target,
  compass: Compass,
  feather: Feather,
  flower: Flower2,
  leaf: Leaf,
  moon: Moon,
  sun: Sun,
  cloud: Cloud,
  mountain: Mountain,
  waves: Waves,
  crown: Crown,
  gem: Gem,
  rocket: Rocket,
  wind: Wind,
};
